config/routes.rb
Rails.application.routes.draw do

  resources :sales

  resources :financings do
    collection do
      get :amortization
    end
  end

  get 'session/login'

  post 'session/authenticate'

  get 'session/logout'

  resources :quotes

  resources :employees

  resources :customers

  resources :vehicles

  root 'session#login'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many  :sales
  belongs_to :vehicle
  belongs_to :employee
  belongs_to :customer
  def taxes
    4.3
  end

  def markup
    10
  end
def total
  wholesale + (wholesale * markup/100) + (wholesale * taxes/100)

end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
        if @quote.status?
          s = Sale.new
          s.tax = @quote.wholesale * 0.043
          s.markup = @quote.wholesale * 0.10
          s.save
          @quote.sales << s
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end
end
  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)

        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
        if @quote.status?
          s = Sale.new
          s.tax = @quote.wholesale * 0.043
          s.markup = @quote.wholesale * 0.10
          s.save
          @quote.sales << s
        end
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:wholesale, :markup, :taxes, :total, :status, :employee_id, :customer_id, :vehicle_id)
    end

  end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wholesale %><br>
    <%= f.text_field :wholesale %>
  </div>
  <div class="field">
    <%= f.label :markup %><br>
    <%= f.text_field :markup %>
  </div>
  <div class="field">
    <%= f.label :taxes %><br>
    <%= f.text_field :taxes %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status ,:as => :check_boxes, collection: [['Pending', 'Sold']] %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select(:employee_id, Employee.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select(:customer_id, Customer.all, :id, :name, prompt: true)%>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.collection_select(:vehicle_id, Vehicle.all, :id, :VIN, prompt: true)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
#encoding: utf-8

<p id="notice"><%= notice %></p>



<h1>Sales Quotes</h1>
<table>
  <thead>
    <tr>
      <th>Wholesale</th>
      <th>Markup</th>
      <th>Taxes</th>
      <th>Total</th>
      <th>Status</th>
      <th>Employee</th>
      <th>Customer</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @quotes.each do |quote| %>
      <tr>
        <td><%= number_to_currency(quote.wholesale) %></td>
        <td><%= number_to_percentage(quote.markup, precision: 0) %></td>
        <td><%= number_to_percentage(quote.taxes, precision: 1) %></td>
        <td><%= number_to_currency(quote.total) %></td>
        <td><%= quote.status %></td>
        <td><%= quote.employee_id %></td>
        <td><%= quote.customer_id %></td>
        <td><%= quote.vehicle_id %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>
</div>
<div id="footer">
  Veronica Paz CIS 4339 Project Copyright © W3Schools.com
</div>

</body>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wholesale:</strong>
  <%= number_to_currency(@quote.wholesale) %>
</p>

<p>
  <strong>Markup:</strong>
  <%= number_to_percentage(@quote.markup, precision: 0) %>
</p>

<p>
  <strong>Taxes:</strong>
  <%=number_to_percentage(@quote.taxes, precision: 1) %>
</p>

<p>
  <strong>Total:</strong>
  <%=number_to_currency(@quote.total) %>
</p>

<p>
  <strong>Status:</strong>
  <%= @quote.status %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer_id %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @quote.vehicle_id %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>