config/routes.rb
Rails.application.routes.draw do

  resources :sales

  resources :financings do
    collection do
      get :amortization
    end
  end

  get 'session/login'

  post 'session/authenticate'

  get 'session/logout'

  resources :quotes

  resources :employees

  resources :customers

  resources :vehicles

  root 'session#login'

end

app/models/financing.rb
class Financing < ActiveRecord::Base

  def self.amortization_table(purchase_price = 0,loan_term = 0,interest_rate = 0)
    Rails.logger.debug "Inputs: #{purchase_price} #{loan_term} #{interest_rate}"

    financing = []
    fixed = purchase_price
    loan = loan_term*12

    (1..loan).each do |t|
      rate =(interest_rate/100)
      @@monthly_payment = (fixed*rate)/((1-(1+rate)**-loan))
      financing<< purchase_price- (@@monthly_payment -(purchase_price * rate))

      previous_amount = purchase_price - (@@monthly_payment - (purchase_price * rate))

      purchase_price = previous_amount

      @@interest_paid = (rate) * @@monthly_payment
      @@principal_paid = (@@monthly_payment-@@interest_paid)

       end
      return financing

  end

  def amortization_table
    return self.class.amortization_table(self.purchase_price,self.loan_term,self.interest_rate)
  end

def  self. monthly_payment
  @@monthly_payment
end
  def self.interest_paid
    @@interest_paid
  end
  def self.principal_paid
    @@principal_paid
  end

end

app/controllers/financings_controller.rb
class FinancingsController < ApplicationController
  before_action :set_financing, only: [:show, :edit, :update, :destroy]

  # GET /financings
  # GET /financings.json
  def index
    @financings = Financing.all
  end

  # GET /financings/1
  # GET /financings/1.json
  def show
    @amortization_array = @financing.amortization_table
  end

  # GET /financings/new
  def new
    @financing = Financing.new
  end

  # GET /financings/1/edit
  def edit
  end

  # POST /financings
  # POST /financings.json
  def create
    @financing = Financing.new(financing_params)

    respond_to do |format|
      if @financing.save
        format.html { redirect_to @financing, notice: 'Financing was successfully created.' }
        format.json { render :show, status: :created, location: @financing }
      else
        format.html { render :new }
        format.json { render json: @financing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financings/1
  # PATCH/PUT /financings/1.json
  def update
    respond_to do |format|
      if @financing.update(financing_params)
        format.html { redirect_to @financing, notice: 'Financing was successfully updated.' }
        format.json { render :show, status: :ok, location: @financing }
      else
        format.html { render :edit }
        format.json { render json: @financing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financings/1
  # DELETE /financings/1.json
  def destroy
    @financing.destroy
    respond_to do |format|
      format.html { redirect_to financings_url, notice: 'Financing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def amortization
    interest_rate = params[:interest_rate]
    loan_term = params[:loan_term]
    purchase_price = params[:purchase_price]
    @amortization_array = @Financing.amortization_table(purchase_price.to_i, loan_term.to_i, interest_rate.to_f)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financing
      @financing = Financing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def financing_params
      params.require(:financing).permit(:purchase_price, :loan_term, :interest_rate)
    end
end

app/helpers/financings_helper.rb
module FinancingsHelper
end

app/views/financings/_amortization_table.erb
<table class="CSSTableGenerator" width="30%">
  <th>Month</th>
  <th>Beginning Balance</th>
  <th>Monthly Payment</th>
  <th>Principal Paid</th>
  <th>Interest Paid</th>

  <%counter=0%>
  <% @amortization_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n+1%></td>
        <td><%= number_to_currency(p.round(2))%></td>
        <td><%= number_to_currency(Financing.monthly_payment.round(2))%></td>
        <td><%= number_to_currency(Financing.principal_paid.round(2))%></td>
        <td><%= number_to_currency(Financing.interest_paid.round(2))%></td>



      </tr>
      <%counter+=1%>
  <% end %>


</table>

app/views/financings/_form.html.erb
<%= form_for(@financing) do |f| %>
  <% if @financing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@financing.errors.count, "error") %> prohibited this financing from being saved:</h2>

      <ul>
      <% @financing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purchase_price %><br>
    <%= f.text_field :purchase_price %>
  </div>
  <div class="field">
    <%= f.label :loan_term %><br>
    <%= f.select :loan_term, (3..5) %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<div id="amortig-table" class="table-format"></div>

app/views/financings/amortization.js.erb
$('#financing-table').html("<%= j (render 'amortization_table') %>")

app/views/financings/edit.html.erb
<h1>Editing Financing</h1>

<%= render 'form' %>

<%= link_to 'Show', @financing %> |
<%= link_to 'Back', financings_path %>

app/views/financings/index.html.erb
#encoding: utf-8
<p id="notice"><%= notice %></p>

<h1>Financing</h1>

<table>
  <thead>
    <tr>
      <th>Purchase Price</th>
      <th>Loan Term Years</th>
      <th>Interest Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @financings.each do |financing| %>
      <tr>
        <td><%=number_to_currency(financing.purchase_price) %></td>
        <td><%= financing.loan_term%></td>
        <td><%= number_to_percentage(financing.interest_rate, precision: 1) %></td>
        <td><%= link_to 'Show', financing %></td>
        <td><%= link_to 'Edit', edit_financing_path(financing) %></td>
        <td><%= link_to 'Destroy', financing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Financing', new_financing_path %>
<div id="footer">
  Veronica Paz CIS 4339 Project Copyright © W3Schools.com
</div>

app/views/financings/new.html.erb
<h1>New Financing</h1>

<%= render 'form' %>

<%= link_to 'Back', financings_path %>

app/views/financings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purchase price:</strong>
  <%= number_to_currency(@financing.purchase_price) %>
</p>

<p>
  <strong>Loan term:</strong>
  <%= @financing.loan_term %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= number_to_percentage(@financing.interest_rate, precision: 1)%>
</p>

<%= render 'amortization_table' %>


<%= link_to 'Edit', edit_financing_path(@financing) %> |
<%= link_to 'Back', financings_path %>