config/routes.rb
Rails.application.routes.draw do

  resources :sales

  resources :financings do
    collection do
      get :amortization
    end
  end

  get 'session/login'

  post 'session/authenticate'

  get 'session/logout'

  resources :quotes

  resources :employees

  resources :customers

  resources :vehicles

  root 'session#login'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
belongs_to :employee
  belongs_to :quote

def total
markup*10 +tax + markup
end
def sales_tax_price
  tax
end

def gross_profit
  markup
end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:markup, :tax)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :markup %><br>
    <%= f.text_field :markup %>
  </div>
  <div class="field">
    <%= f.label :tax %><br>
    <%= f.text_field :tax %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
#encoding: utf-8
<p id="notice"><%= notice %></p>

<h1>Total Sales</h1>

<table>
  <thead>
    <tr>
      <th>Markup</th>
      <th>Tax</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= number_to_currency(sale.markup) %></td>
        <td><%= number_to_currency(sale.tax) %></td>
        <td><%= number_to_currency(sale.total) %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br>

<th><b>Total Revenue:</b></th>
<td><%= number_to_currency(@sales.map{|item| item.total}.reduce(0, :+)) %></td>
</tr>
<br>
<br>

<th><b>Total Sales Tax:</b></th>
<td><%= number_to_currency(@sales.map{|item| item.sales_tax_price}.reduce(0, :+)) %></td>
</tr>

<br>
<br>

<th><b>Gross Profit:</b></th>
<td><%= number_to_currency(@sales.map{|item| item.gross_profit}.reduce(0, :+)) %></td>
</tr>

<br>
<br>
<%= link_to 'New Sale', new_sale_path %>
<div id="footer">
  Veronica Paz CIS 4339 Project Copyright © W3Schools.com
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Markup:</strong>
  <%= @sale.markup %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @sale.tax %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>